version: '3'
services:
  web:
    build: ./docker/web
    container_name: web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/twitter_pj
    working_dir: /var/www/twitter_pj
    privileged: true
    depends_on:
      - db
      - s3
    links:
      - s3 # minioと接続するために、minioのコンテナー名を指定することで名前解決する

  db:
    build: ./docker/db
    container_name: db
    ports:
      - 3366:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: twitter
      MYSQL_PASSWORD: twitter
      MYSQL_DATABASE: twitter_db
    volumes:
      - db-data:/var/lib/mysql
  s3:
    image: minio/minio
    container_name: s3
    hostname: s3
    ports:
      - "9000:9000"
    volumes:
      - ./docker/minio/data:/data
    command: server /data
    environment:
      MINIO_ACCESS_KEY: local_test_s3_access_key
      MINIO_SECRET_KEY: local_test_s3_secret_key
volumes:
  db-data:
    driver: local

# networks:
#   bridge2:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.16.238.0/24